### ISSUE TITLE
Trained Model

### ISSUE THREAD

**Issue by pribadihcr** [linyq2117/TagCLIP#1]
Hi, Is there a link to download the trained model?

Big Thanks

**Comment by linyq2117** [comment]
Thanks for your interest!

Our method is based on the original CLIP and is training-free. The pre-trained CLIP model can be downloaded from the official link [ViT-B-16](https://openaipublic.azureedge.net/clip/models/5806e77cd80f8b59890b7e101eabd078d9fb84e6937f9e85e4ecb61988df416f/ViT-B-16.pt), which can be found in README.
