### ISSUE TITLE
Question about Using Linear Layer on Penultimate Features (Eq. 9)

### ISSUE THREAD

**Issue by NanAlbert** [linyq2117/TagCLIP#2]
I'm intrigued by this work. However, I have a small concern regarding the implementation of Equation 9. Typically, the Linear layer is intended for mapping the last layer's features, yet in the article, it is applied to the features of the penultimate layer. Is this approach appropriate, and can it yield effective results?

**Comment by linyq2117** [comment]
Thanks for your interest!

The original expression may cause some misunderstandings. In fact, `x_dense` is first defined in Equation 8, which represents the output of the last layers but neglects the self-attention operation. Therefore, the feature space of `x_dense` used in Equation 9 is well aligned with the original CLIP. The `penultimate` used here mainly aims to highlight the ignorance of self-attention in the last layer but is indeed misleading. Thanks for your feedback.
