### ISSUE TITLE
Question about the code of "ResidulaAttentionBlock" and "multi_head_attention".

### ISSUE THREAD

**Issue by yeelinsen** [linyq2117/TagCLIP#3]
Great work! I have some question about the code:
1. I noticed that you slightly modified the code of "ResidualAttentionBlock" at https://github.com/linyq2117/TagCLIP/blob/c32b640f3a1cf840e23e4ca8b55aa2b35d086fc5/clip/clip_model.py#L219  What is the meaning of `if x.shape[0] != 77 and mask is not None:` and the code within the code block.
2. Why you choose a `MultiheadAttention2` instead of `nn.MultiheadAttention` at  https://github.com/linyq2117/TagCLIP/blob/c32b640f3a1cf840e23e4ca8b55aa2b35d086fc5/clip/clip_model.py#L219 ?

**Comment by linyq2117** [comment]
Hi, thanks for your interest!

1. The `ResidualAttentionBlock` is used in both image encoder and text encoder. We only perform mask attention in the last layer of the image encoder so the dim 77 is used to neglect the relevant blocks in the text encoder (the token length in CLIP text encoder is 77 as default).

2. The `MultiheadAttention2` is basically consistent with `nn.MultiheadAttention`. We make few modifications to enable it to return q, k, v.

**Comment by linyq2117** [comment]
Closed for inactivity.
